### ISSUE TITLE
UnicodeEncodeError in handleMessageReplies L557

### ISSUE THREAD

**Issue by erocs** [Pentom/modmail_ticketmanager#7]
2015-05-05 04:12:55.981910 - Error when attempting to review modmail on line number 212.  Exception:  <type 'exceptions.UnicodeEncodeError'>
**\* print_tb:
  File "modmail_ticketmanager.py", line 212, in processModMail
    shouldContinueProcessing = processModMailRootMessage(debug, mail, inExtendedValidationMode)
**\* print_exception:
Traceback (most recent call last):
  File "modmail_ticketmanager.py", line 212, in processModMail
    shouldContinueProcessing = processModMailRootMessage(debug, mail, inExtendedValidationMode)
  File "modmail_ticketmanager.py", line 346, in processModMailRootMessage
    messageReplyReturn = handleMessageReplies(debug, ticketId, rootMessageId, rootReplies, messageNewestAge)
UnicodeEncodeError: 'ascii' codec can't encode character u'\uff0d' in position 77: ordinal not in range(128)
**\* print_exc:
Traceback (most recent call last):
  File "modmail_ticketmanager.py", line 212, in processModMail
    shouldContinueProcessing = processModMailRootMessage(debug, mail, inExtendedValidationMode)
  File "modmail_ticketmanager.py", line 346, in processModMailRootMessage
    messageReplyReturn = handleMessageReplies(debug, ticketId, rootMessageId, rootReplies, messageNewestAge)
  File "modmail_ticketmanager.py", line 557, in handleMessageReplies
    replyBody      = str(reply.body)
UnicodeEncodeError: 'ascii' codec can't encode character u'\uff0d' in position 77: ordinal not in range(128)

**Comment by Pentom** [comment]
Able to reproduce.
